#!/usr/bin/env python3
"""Read the generated DBM0 module's song and pattern data.

    python3 dbmpatt.py part1.dbm [part3.dbm ...]

Why this file exists: the 68K frame routine `__refresh` ends each scene when
`dbplayer.library` (LVO -60) reports signal 1, and nothing in the PowerPC code
ever sets that flag. So **the show's timeline lives in the music**, and the music
is generated by code the harness already runs byte-exactly. Decoding the
patterns is therefore the offline route to the scene boundaries.

The DigiBooster Pro 2 "DBM0 Format Specification 1.4" describes the container.
As always the generated file is the authority where they disagree — the notes in
NOTES.md record where they do.
"""
import collections
import struct
import sys

ROWMAX = 4096


def chunks(d):
    """DBM0 header then plain IFF chunks. The 4 bytes before DBM0 are the
    generator's own u32 length prefix, not part of the format."""
    o = 0
    if d[4:8] == b'DBM0':
        o = 4
    if d[o:o + 4] != b'DBM0':
        raise ValueError(f'not a DBM0 module ({len(d)} bytes, starts {d[:8].hex()}) '
                         '— an empty buffer usually means the synth run timed out')
    ver = struct.unpack_from('>H', d, o + 4)[0]
    o += 8
    out = []
    while o + 8 <= len(d):
        cid, n = d[o:o + 4], struct.unpack_from('>I', d, o + 4)[0]
        if not cid.isalnum() or o + 8 + n > len(d):
            break
        out.append((cid.decode('latin1'), o + 8, n))
        o += 8 + n + (n & 1)
    return ver, out


def songs(d, off, n):
    res, o = [], off
    while o < off + n:
        name = d[o:o + 44].split(b'\0')[0].decode('latin1')
        cnt = struct.unpack_from('>H', d, o + 44)[0]
        orders = list(struct.unpack_from(f'>{cnt}H', d, o + 46))
        res.append((name, orders))
        o += 46 + cnt * 2
    return res


def patterns(d, off, n, channels):
    """Unpack PATT. Per pattern: UWORD rows, ULONG packed size, packed stream.

    The stream is a run of entries: a zero byte ends the row, otherwise the byte
    is channel+1 and a mask byte says which of note / instrument / effect1 /
    param1 / effect2 / param2 follow, in that order.
    """
    pats, o = [], off
    while o + 6 <= off + n:
        rows, size = struct.unpack_from('>HI', d, o)
        o += 6
        if not 0 < rows <= ROWMAX or o + size > off + n:
            break
        end, row, cells = o + size, 0, []
        while o < end:
            t = d[o]; o += 1
            if t == 0:
                row += 1
                continue
            ch, m = t - 1, d[o]; o += 1
            f = {}
            for bit, key in ((1, 'note'), (2, 'inst'), (4, 'fx1'),
                             (8, 'p1'), (16, 'fx2'), (32, 'p2')):
                if m & bit:
                    f[key] = d[o]; o += 1
            if 'fx1' in f or 'fx2' in f:
                cells.append((row, ch, f))
        pats.append({'rows': rows, 'cells': cells})
        o = end
    return pats


SIGNAL_FX, ADVANCE = 7, 1     # effect 7 = set signal; value 1 = next scene


def timeline(pats, orders, speed=6, bpm=125):
    """Walk the order list and time it, returning the signal-1 positions.

    Effect 7 is the signal command — see NOTES.md for how that was established
    (it is not tremolo, whatever ProTracker numbering would suggest). Effect 15
    is read as ProTracker `Fxx`: below 32 it sets ticks-per-row, at or above it
    sets BPM. That reading is a hypothesis; the row positions below are not.
    """
    events, row, t = [], 0, 0.0
    for oi, p in enumerate(orders):
        pat = pats[p]
        fx = {}
        for r, c, f in pat['cells']:
            for k, pk in (('fx1', 'p1'), ('fx2', 'p2')):
                if k in f:
                    fx.setdefault(r, []).append((f[k], f.get(pk, 0)))
        for r in range(pat['rows']):
            for e, v in fx.get(r, ()):
                if e == 15 and v:
                    if v < 32: speed = v
                    else: bpm = v
                elif e == SIGNAL_FX and v == ADVANCE:
                    events.append({'row': row + r, 'order': oi, 'pattern': p,
                                   'patrow': r, 'seconds': round(t, 3),
                                   'ticks50': round(t * 50)})
            t += (2.5 / bpm) * speed
        row += pat['rows']
    return events, row, t


def main():
    for path in sys.argv[1:]:
        d = open(path, 'rb').read()
        ver, cs = chunks(d)
        print(f'\n=== {path}  version {ver:#06x}  {len(d)} bytes')
        print('    chunks: ' + ', '.join(f'{c}({n})' for c, _, n in cs))
        by = {c: (o, n) for c, o, n in cs}
        if 'INFO' in by:
            o, _ = by['INFO']
            ins, smp, sng, pat, chn = struct.unpack_from('>5H', d, o)
            print(f'    instruments {ins}  samples {smp}  songs {sng}  '
                  f'patterns {pat}  channels {chn}')
        orders = []
        if 'SONG' in by:
            for name, orders in songs(d, *by['SONG']):
                print(f'    song {name!r}: {len(orders)} orders {orders}')
        if 'PATT' not in by:
            print('    no PATT chunk in this dump')
            continue
        pats = patterns(d, *by['PATT'], chn)
        print(f'    unpacked {len(pats)} patterns, '
              f'rows {[p["rows"] for p in pats]}')
        use = collections.Counter()
        for p in pats:
            for _, _, f in p['cells']:
                for k in ('fx1', 'fx2'):
                    if k in f:
                        use[f[k]] += 1
        print('    effect usage: ' + ', '.join(
            f'{e:#04x}x{n}' for e, n in sorted(use.items())))
        ev, rows, secs = timeline(pats, orders)
        print(f'    {len(ev)} scene advances over {rows} rows '
              f'(~{secs:.1f}s at the assumed tempo)')
        prev = 0.0
        for i, e in enumerate(ev):
            print(f'      [{i:2}] row {e["row"]:5}  order {e["order"]:2} '
                  f'pat {e["pattern"]:2} row {e["patrow"]:3}   '
                  f't={e["seconds"]:8.3f}s  ({e["ticks50"]:5} ticks)  '
                  f'held {e["seconds"] - prev:7.3f}s')
            prev = e['seconds']


if __name__ == '__main__':
    main()
