// AUTO-GENERATED from unpacked/sonnet_img.bin — resource archive at VA 0x4170da.
// 52 length-prefixed blocks: {u32 len; u8 data[len]}. FUN_00401c3b(id) walks this chain.
// res 0..27  = texture programs (texgen VM)
// res 28..35 = scene descriptors (8 scenes)
// res 36..51 = per-sub-object descriptors
const B64 = [
  "AQABAAEQDgAHAAQvUnUAEAAHAAIZshoABwACGz8H/wAAAAcABwEBABwADgEBYwn/AAEBAwj/AAEBZAz/AAEBARUABwEEAACTjhMABwEE7ACQzQf/AAEADP8AAgEADAAHAggII83NH7DgAAn/AAIBAQj/AAIBHg==", // 0 len=118
  "AQABAAEOAwAHAAhxas3NW7+V/xAABwACBX8H/wAAACEABwEQMvrNzQAAAABbv5X/l83NzQn/AAEBAgf/AAEADgAIAgRbv5UAHwAIAigOf83NW7+V/wLNzc2kFHgsTlxFsVnbS/pi3pHOuKXCdbJIriuzDaQUIAAIAgh/fwDNW7+V/wr/AAIE/////w4ACAEEW7+VAA4ACAAEW7+VAAP/AAIAA/8AAQA=", // 1 len=167
  "AQABAAEKDAAHAAgII83NANf//wf/AAAADgAHAQQ0yyf/A/8AAQAJ/wABAQEI/wABATwQAAcAAhkUDP8AAAEBFQAHAAREAWZ3DP8AAAEA", // 2 len=78
  "ASAAIAABAwAHAAhrZ83NQqho/w==", // 3 len=19
  "ASAAIAABDgAHAAT/////", // 4 len=15
  "ARAAEAAFDgAHAAT/////B/8AAAAOAAcBBP////8K/wABBP////8MAAgBCAoezc3/////", // 5 len=51
  "AQgACAAFDgAHAAT/////B/8AAAAK/wABBP////8OAAcBBP////8MAAgBCBAyzc3/////", // 6 len=51
  "AQABAAEGDgAHAAT/////B/8AAAAK/wABBP////8OAAcBBP////8DAAgBCCVpzc3/////GQAIAQEF", // 7 len=57
  "AQABAAEPDgAHAAT/////B/8AAAAK/wABBAAAAP8DAAgBCHtHzc3/////B/8AAQAK/wACBAAAAP8J/wACAQMiAAgCEAAAD/7Nzc3N////AAAAAP8H/wACAAr/AAMEAAAA/yIACAMQAAD9/s3Nzc3/////AAAAAAn/AAMBAwT/AAMBAQr/AAAE/////x4ACAABzQ==", // 8 len=145
  "AQABAAENCv8AAAT/////DgAIAAQAAAAAHwAIACAKf83NAAAA/wLNzc0E+R2/Y47UYO0y2Ba7DhYMAAoE+SAACAAIj2cAzQAAAP8H/wAAAAMABwEIuh7Nzf////8QAAcBAgKAHAAHAQEUB/8AAQAiAAcCEAAA/v7Nzc3N/////wAAAAAJ/wACAQEJ/wABAQEI/wACATs=", // 9 len=149
  "AQABAAEbDgAHAAT/////B/8AAAAOAA8BBEQvIgAK/wABBP////8fAAgBIAp/zc1ELyL/As3NzQ5/WzC4A+8wvoDTlMbRi+020w5/IAAIAQh/fwDNRC8i/wf/AAEADAAHAggIKM3N/////wn/AAIBARYABwICGQAE/wABAQEK/wAABP////8QAAcAAhliGgAPAAIKqhAABwACDM8WAA8AAgDvB/8AAAAOAAcBBEQvIv8J/wABAQEI/wABAT8J/wABAQAI/wABASQH/wABAA4ABwIE/////wP/AAIAA/8AAQAWAA8BAg8A", // 10 len=231
  "AQACAAgBEQAHAAjNzc3Nzc3NzQ==", // 11 len=19
  "ASAAIAAAAAA=", // 12 len=8
  "AQABAAEHAwAHAAiHYM3N6M48/wf/AAAABwAHAQEACf8AAQEDHAAHAQEgDP8AAQEBEwAHAQQKAZvN", // 13 len=57
  "AQABAAEODAAHAAgLLs3Nb6u//wf/AAAADAAHAQgZJ83N/////wn/AAEBAQf/AAAAAwAHAQhvNs3N/////wn/AAEBAwj/AAEBPAn/AAEBAQj/AAEBCgf/AAEADAAHAggJHs3N/////wn/AAIBAwj/AAEBEQ==", // 14 len=115
  "ARAAEAAIDgAHAAT/////B/8AAAAOAA8BBP///wAMAAgBCAgjzc3/////GgAIAQIFHRoACAECBbATAAgBBBgBrc0K/wABBP////8=", // 15 len=74
  "AQACAAICEAAHAAIZxgoABwABzQ==", // 16 len=19
  "AQABAAEIAwAHAAjyMM3Nn77GABMABwAEGgGVzQf/AAAABwAHAQEAEAAHAQIZLRwABwEBFQn/AAEBAQj/AAEBOA==", // 17 len=64
  "AQABAAEIAwAHAAgWO83NRlVU/xwABwABFBMABwAErQCFzQf/AAAAAwAPAQjIPM3Ne5OR/wn/AAEBBAz/AAEBARUABwEEkQCBfw==", // 18 len=73
  "AQABAAETAwAPAAi8GM3NQtWl/wr/AAAE/////wf/AAAAA/8AAQADAAcACFIZzc18mp7/CP8AAQFkCf8AAQEAEwAHAATzAKXNEwAHAQQPAY/NEwAHAQTnAH/NCv8AAAT///8AB/8AAQAHAAcCAQEcAAICARUJ/wACAQMTAAICBDYBjc0H/wACAA4ABwMEAP///wj/AAMBCg==", // 19 len=151
  "AQABAAEVAwAPAAi8GM3NQtWl/wr/AAAE/////wf/AAAAA/8AAQADAAcACFIZzc18mp7/CP8AAQFkCf8AAQEAEwAHAATzAKXNEwAHAQQPAY/NEwAHAQTnAH/NCv8AAAT///8AB/8AAQAHAAcCAQEcAAICARUJ/wACAQMTAAICBDYBjc0H/wACAA4ABwMEAP///wj/AAMBCgT/AAMBARUABwAEPgF/gQ==", // 20 len=166
  "AQABAAEBDgAHAAT/////", // 21 len=15
  "AYAAgAAGAwAHAAgaUM3NNzc3/xoABwACHNMH/wAAAAwABwEICCPNzTc3N/8J/wABAQII/wABATk=", // 22 len=56
  "AYAAgAAJAwAHAAhXC83N/////wf/AAAAHwAHASILf83N/////wLNzc05O4IZnI5ibG7lrZKtHdsp5+sz5Tk7IAAHAQg/pADN/////xkABwEBExMABwEEpAB/zQn/AAEBAgT/AAEBARkABwABBg==", // 23 len=109
  "AYAAgAALAwAHAAgAbs3N/////wf/AAAAHwAHARoHf83N/////wLNzc0RG8kPyIzt30XIC1oRGyAABwEIf38Azf////8fAAcBFgV/zc0AAAD/B83NzTNFXDpIbAx1M0UTAAcBBD4Af80ZAAcBAQEJ/wABAQIE/wABAQEZAAcAARATAAcABJYAf80=", // 24 len=137
  "AYAAgAAGHwAHABQEf83NUFBQ/wLNzc0rsWC1gukrsSAABwAIS7cAzVBQUP8fAAcAIgt/zc3/////As3NzTEndDWKE+sT35LLnNPhppSAinxTMScgAAcACKJgAM3/////GQAHAAEIFgAHAAIP8Q==", // 25 len=109
  "AYAAgAAEAwAHAAiUOc3N/////xMABwAE0gCszRkABwABDhMABwAEBQGzzQ==", // 26 len=43
  "AQABAAEDAwAHAAg2Q83N//XX/xoABwACGT8TAAcABEcBk80=", // 27 len=35
  "AQHNzMw9AAAAAAAAgD8AAAAAAAAAAc0AAAAAzc3Nzc3Nzf/IyAAAAPpDAABIRCwBAAAAAAAAAADIQwAAAAD/FwAAgEAAAMA/AACAQEATEgIAAABQAAAA1EIAACBCAADAQQAAFkMAAAAAAAAWQ83MTEAAACBD", // 28 len=117
  "AgDNzc3NAAAAAAAAgD8AAAAAgD8AAc0DAAAAeP///wD6AP/IyAAAAMhDAAAvRJABAAAAAMjDAAD6QwAAyEP/FwAAQEAAAAA/AABAQEATEgACAwE=", // 29 len=83
  "AwDNzc3NAAQBAAAAgD8BAQAAAAAAAc0AAAAAzc3Nzc3Nzf/IhgAAAPpDAABIRCwBMgAAAAAAAADIQwAAyEP/FgAAoEAAAMA/AACgQEATEjDAAQAKAAAAAAAAAAAAAAAWwwAAyEIAAAAAAADIQgAAAEAAAEBBBQAAAJbDAACgQQAAlkMAABZDAAAAAAAAFkMAAOA/AABAQQUAAACWQwAAoEEAAJZDAAAWQwAAAAAAABZDAAAgQAAAQEEKAAAAAAAAAKBBAACWQwAAekMAAAAAAAAWQwAAAEAAAEBBAAEAAAAAAAAAAAAAAAAAAJZDAAAAAAAAlkPNzMw+AAAAAAAAAAAAAAAAmpkZPgAAAAAAAKBCAAAAAAABAADIQs3MzD4A", // 30 len=288
  "AQDNzc3NAAAAAAAAgD8AAQAAAAAAAc0DAAAAtP///wDIAP/IyAAAYDhFAIA7RSwBAAAAAAAAAADcQwAAyEP/FwAAoEBvEoM6AACgQEATEgBOAAAAAAAAAACWQwAAAAAEAAAAyELNzMw+AQ==", // 31 len=106
  "AwDNzc3NAQEAAAAAgD8AAQAAgD8AAc0AAAAAzc3Nzc3Nzf+iUQAAABZEAAB6RCADFAAAABbEAABIQwAAlkP/GQAAQEAAAAA/AABAQEAREhVgAQAAAEhCAAAAAAAAyMLNzc3NAADwQgAAIEEAAABBAAAAQwEAAABIQgAAAAAAAMjCAACAPwAAAAAAAIA/zcyMPwAAIEEAAEjDAAAMQwAAyEJAAAAAyELNzMw+AQ==", // 32 len=172
  "AgDNzc3NAAEAAQAAgD8AAAAAAAAAAwECAAAA8MjIyACWAAFHowAAAC9EAAB6RCwBFAAAABbEAADIQwAAlsPvGAAAgEAAAMA/AACAQEAUEtgChQAFAAAAyEIAAAAAAACWwwAAyEIAAAAAAABIQgAAAD8AAIBAAADwwgAAIEEAAEhCMzMzPs3MTD4AAAAACswAAEA/", // 33 len=147
  "AgDNzc3NAAEAAAAAgD8AAAAAAAAAEAAAAAAAzc3Nzc3NzdDNyQAAAEhCAACWQywBZAAAAMhCAAB/QwAAyEPoFgAAQEDNzMw/AABAQIAUElAADQAUAAAAAAAAAAAAAAAAAAAAr0MAAAAAAACvQwAAAD8AACBB", // 34 len=117
  "AgDNzc3NAAAAAAAAgD8AAAAAAAAAAc0CAAAAgP///wAAAeGiUQAAAEhDAAB6RCwBFAAAAAAAAAB6RAAAAAD/GgAAAEAAAIA/AAAAQIAbGwADAQA=", // 35 len=83
  "LQADAADdwVpCTsIowMFAAACAQt3BWkJOwry/wUAAAEBDSENaQiQ+vL/BQAAA", // 36 len=45
  "LQADAABcQlZCu0FSvpZAAAAAQmFDCULKQas+lkAAAMBCGEPMQqXCQD+sQAAA", // 37 len=45
  "LQADAADYQklBGEOduxFBAABAQghDzkJlwgk/KUEAAMBC3cKCQTjDOD0nQQAA", // 38 len=45
  "HwACAAAYRHBCMcOOPZ5AAADAQuVCxUFOwo49nkAAAA==", // 39 len=31
  "HwACAACRwpVABMMTv9NAAACAQh/ClUAOwxO/y0AAAA==", // 40 len=31
  "OwAEAAB3QPRAhsC6Pj9BAACAQvw/T0HrP4A/HEEAAOBC/j9/QfE/xj8cQQAAIEPIQC5B4MAWP0FBAAA=", // 41 len=59
  "OwAEAADOwXlDAAAAAGnAAACAQjZDh0OIw/A+A8AAAABDv0GXQ8PD8D6LvgAAQEOSwV9DtcLPPfu9AAA=", // 42 len=59
  "HwACAAAXxLNCdkMgPmlBAACAQtDDIkLRQhg8Y0EAAA==", // 43 len=31
  "LQADAABWQylDisIWP5VAAACAQqRCCENlwlC+q0AAAABDWcIDQ5nCdj6VQAAA", // 44 len=45
  "HwACAAArwzBBxcInvZBBAAAAQ9/DNkJTwye9k0EAAA==", // 45 len=31
  "OwAEAACRwtlCBkJVP6xAAAAAQwTDnEEDQoq/5UAAAIBDYcPdQrVCbD/8QAAAoEOYwxlDKUItPwFBAAA=", // 46 len=59
  "LQADAABHQ5xBdMMwvnpAAACAQqZCIUK9w4a+j0AAAABDQsJ6QsLDtr3PQAAA", // 47 len=45
  "LQADAAClwEdCvsPHu9BAAACAQnBBNkKVw4g9uEAAAABDjsIUQizDiD3mQAAA", // 48 len=45
  "SQAFAAAiw1JCREOtPgxBAABAQuXC9EHgQq0+GEEAAMBCAMN7QeQ/ijwYQQAAEENwwoRBCMOKPD1BAABAQ7PCfEIww6I+U0EAAA==", // 49 len=73
  "LQADAADlQc1CHkA1v/Q/AAAAQzPCiULiQYW99D8AAIBDZcOLQp5Bhb3bPwAA", // 50 len=45
  "LQADAACVwaNC+cKqvKZAAAAAQ8FCo0KvQqq8pkAAAIBDf0F6QgNDqrymQAAA", // 51 len=45
];

function dec(s) {
  const bin = typeof atob === 'function' ? atob(s) : Buffer.from(s, 'base64').toString('binary');
  const a = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) a[i] = bin.charCodeAt(i);
  return a;
}
export const RESOURCES = B64.map(dec);
export function resource(id) { return RESOURCES[id]; }

