// assets.js — build the demo's content on the machine that is watching it.
//
// The original ships 4,178 bytes of resource archive inside a 65,536-byte
// executable and generates everything else at startup, behind the progress screen
// in preloader.js. This module makes the web port do the same:
//
//   textures    js/texgen.mjs over js/resources.mjs      (already the case — the
//               scene objects call `texgenImage()` and never fetch a PNG)
//   font atlas  js/fontgen.js — texgen op 17, ported to canvas.  Was the last
//               asset that had to ship as an image; see the header there.
//   audio       audio/{module,synth,codec0,writexm}.mjs, which rebuild the XM from
//               the four embedded streams, byte for byte.
//
// Measured payload, gzipped, for the two things this module replaces:
//
//   font atlas   baked/tex/11.png        94,754 B   ->  generated, 0 B
//                baked/tex_2x/11.png    214,113 B   ->  generated, 0 B
//   module       extracted/sonnet.xm    708,260 B   ->  unpacked/sonnet_img.bin,
//                                                       69,480 B  (and that file
//                                                       is the whole 541 KB image,
//                                                       not a trimmed extract)
//
// `?assets=baked` keeps the old download path in full. It is the fallback for a
// machine with no Times New Roman, and it is the regression corpus: the generated
// atlas is diffable against baked/font_atlas_<N>x.png and the generated module is
// diffable against extracted/sonnet.xm.

import { makeAtlas as generateAtlas, hasTimesNewRoman } from './fontgen.js';
import { loadAtlas } from './text.js';
import { installBuffer, preloadFile, hasFile } from './node_compat.js';

/** The 28 texture programs in the resource archive. */
export const NUM_TEXTURES = 28;

/**
 * The font atlas: generated by default, downloaded on `?assets=baked` or when the
 * machine has no Times New Roman.
 *
 * @returns {{atlas: object, source: string, ms: number, note: string|null}}
 */
/**
 * The baked atlas exists at 1x and 2x only. Anything finer has to be generated, so
 * a request the bake cannot satisfy must SAY so rather than quietly handing back a
 * coarser texture that still renders and still lays out correctly (the consumer
 * scans for glyph boxes, so a downgrade is invisible in every automated check we
 * have — it would only show as slightly soft type).
 */
function bakedAtlasPath(root, scale) {
  const have = scale >= 2 ? 2 : 1;
  if (scale > have) {
    console.warn(`assets: no baked font atlas at ${scale}x — using the ${have}x bake. ` +
                 `Type will be softer than requested; the generated path supports ${scale}x.`);
  }
  return `${root}baked/tex${have > 1 ? '_2x' : ''}/11.png`;
}

export async function buildAtlas(d3d, { root, mode, scale }) {
  const t0 = performance.now();
  if (mode !== 'baked') {
    if (hasTimesNewRoman()) {
      const atlas = generateAtlas(d3d, scale);
      return { atlas, source: 'generated', ms: performance.now() - t0, note: null };
    }
    // Deliberately loud rather than silently substituting a different serif: the
    // atlas would still WORK (the consumer scans it for glyph boxes, so metrics do
    // not matter — re/gen/TEXGEN_PORT.md §18), but it would not be the original's
    // type, and that is worth knowing about.
    console.warn('assets: no Times New Roman on this machine — ' +
                 'falling back to the baked font atlas');
    const atlas = await loadAtlas(d3d, bakedAtlasPath(root, scale));
    return {
      atlas, source: 'baked-fallback', ms: performance.now() - t0,
      note: 'Times New Roman is not installed; used baked/font_atlas',
    };
  }
  const atlas = await loadAtlas(d3d, bakedAtlasPath(root, scale));
  return { atlas, source: 'baked', ms: performance.now() - t0, note: null };
}

/**
 * The module. Generated: read `unpacked/sonnet_img.bin` and run the audio port's
 * `buildXm()`, which reconstructs `extracted/sonnet.xm` byte for byte.
 *
 * @returns {{xm: Uint8Array, source: string, ms: number}}
 */
export async function buildModule({ root, mode, party }) {
  const t0 = performance.now();
  if (mode === 'baked') {
    const url = root + (party ? 'extracted/sonnet_partypan.xm' : 'extracted/sonnet.xm');
    const xm = new Uint8Array(await fetch(url).then((r) => r.arrayBuffer()));
    return { xm, source: 'baked', ms: performance.now() - t0 };
  }

  // The audio modules import `node:fs` statically, so Buffer has to exist and the
  // image has to be registered before they are EVALUATED — hence installBuffer()
  // and preloadFile() ahead of the dynamic import, not after it.
  installBuffer();
  const img = new URL(root + 'unpacked/sonnet_img.bin', location.href).href;
  if (!hasFile(img)) await preloadFile(img);      // main.js prefetches it at page load
  const { buildXm } = await import('../../work/audio/writexm.mjs');
  const b = buildXm({ panMode: party ? 'party' : 'correct' });
  return {
    xm: new Uint8Array(b.buffer, b.byteOffset, b.byteLength),
    source: 'generated', ms: performance.now() - t0,
  };
}

/**
 * Run the texture programs, reporting after each. `texgenImage` memoises into
 * FUN_00416036's cache (`_texgenCache` in scene7.js), so the scene builds that
 * follow find everything ready and the progress bar reflects the work that
 * actually happens rather than a guess about it.
 *
 * `plan` entries are either a bare program id (generate at scene7's current
 * texture scale) or `{id, scale}` — which is what `scene7.texturePlan()` returns,
 * so the terrain heightmap programs are warmed at 1x, the resolution they are
 * actually consumed at, instead of being generated twice.
 *
 * @param {(id:number, done:number, total:number)=>Promise<void>|void} onEach
 */
export async function warmTextures(texgenImage, plan, onEach) {
  const times = [];
  for (let i = 0; i < plan.length; i++) {
    const e = plan[i];
    const id = typeof e === 'number' ? e : e.id;
    const scale = typeof e === 'number' ? undefined : e.scale;
    const t0 = performance.now();
    // `undefined` lets texgenImage's own default (the global scale) apply.
    texgenImage(id, scale);
    times.push({ id, scale, ms: performance.now() - t0 });
    if (onEach) await onEach(id, i + 1, plan.length);
  }
  return times;
}

/**
 * Every program except 11. Texture 11 is the font strip, and its only op is 17 —
 * the GDI atlas — which fontgen.js produces directly; running the program would
 * just allocate a black 2048x512 layer for nothing.
 */
export function allTextureIds() {
  const ids = [];
  for (let i = 0; i < NUM_TEXTURES; i++) if (i !== 11) ids.push(i);
  return ids;
}
