// stages.js — which half of the pipeline is a port and which is a recording.
//
// The restoration proceeds one stage at a time, and every stage spends a while
// with a working implementation on both sides: the original's recorded output,
// and the port that has to reproduce it. Being able to run a mixture is what
// makes a difference attributable — a wrong picture with computed animation
// over recorded emission says something a wrong picture with both computed does
// not.
//
// `web/README.md` used to describe that arrangement as though it existed. It
// did not; there was a table of prose and no mechanism. This is the mechanism,
// and the table is now generated from it.
//
// A STAGE WITH NO IMPLEMENTATION ON A SIDE SAYS SO. Asking for
// `?anim=computed` when there is no computed animation reports an error and
// keeps the recording; it does not quietly render the recording and let the
// page look like it honoured the request. That distinction is the whole reason
// to have this rather than a handful of booleans — a switch that silently
// ignores you is worse than no switch, because it makes a green check mean
// nothing.

/**
 * The pipeline, in the order data flows through it.
 *
 * `computed` and `recorded` hold a one-line description of what that side is,
 * or null when that side does not exist. Both sides null is not a thing; a
 * stage exists because at least one of them does.
 */
export const PIPELINE = [
  {
    name: 'tables',
    what: 'the four lookup tables the 68K bootstrap builds',
    computed: 'rebuilt from the executable\'s own float constants (tables.js)',
    recorded: null,
  },
  {
    name: 'textures',
    what: '69 procedural textures',
    computed: 'the texture VM over the intro\'s bytecode (texturevm.js)',
    recorded: 'the exported PNGs under data/textures/',
  },
  {
    name: 'geometry',
    what: 'the mesh builder\'s vertices and faces',
    computed: 'built from seg3 and seg4 (geom.js) — 181/181 nodes vs geodump',
    recorded: 'baked into data/draws.json',
  },
  {
    name: 'scene',
    what: 'the scene VM\'s node graph',
    computed: 'decoded from the stream (scene.js) — 29/29, 395/395 nodes',
    recorded: 'baked into data/draws.json',
  },
  {
    name: 'anim',
    what: '_calc_matrix — keyframes to per-node transforms',
    computed: 'all three passes, stepped per tick (anim.js) — 2,783 blocks exact',
    recorded: 'baked into data/draws.json',
  },
  {
    name: 'emit',
    what: '_show_scene — clipping and projection to primitives',
    computed: 'the node walk, clipper and projection (render.js, engine.js)',
    recorded: 'data/draws.json, five frames per scene',
  },
  {
    name: 'raster',
    what: 'the Warp3D surface the intro uses',
    computed: 'translated to WebGL2 (warp3d.js)',
    recorded: null,
  },
  {
    name: 'audio',
    what: 'the softsynth and the DigiBooster replayer',
    computed: 'both modules generated byte-exactly (synth.js, dbmplayer.js)',
    recorded: null,
  },
];

const BY_NAME = new Map(PIPELINE.map((s) => [s.name, s]));

/**
 * Resolve `?stage=computed|recorded` overrides against what exists.
 *
 * Defaults to `computed` wherever there is a port and `recorded` otherwise, so
 * the page always shows the most finished thing it can without being asked.
 *
 * @returns {{choice: Object<string,string>, errors: string[]}}
 */
export function resolveStages(params) {
  const choice = {};
  const errors = [];
  for (const s of PIPELINE) {
    const want = params.get(s.name);
    if (want && want !== 'computed' && want !== 'recorded') {
      errors.push(`${s.name}=${want}: expected computed or recorded`);
    } else if (want && !s[want]) {
      const has = s.computed ? 'computed' : 'recorded';
      errors.push(`${s.name}=${want}: not implemented — only ${has} exists`);
    } else if (want) {
      choice[s.name] = want;
      continue;
    }
    choice[s.name] = s.computed ? 'computed' : 'recorded';
  }
  return { choice, errors };
}

/** The provenance map `window.__demo.state()` reports, one entry per stage. */
export function provenance(choice, extra = {}) {
  return Object.fromEntries(PIPELINE.map((s) => {
    const side = choice[s.name];
    return [s.name, {
      side,
      what: s.what,
      how: s[side] ?? 'not implemented',
      switchable: Boolean(s.computed && s.recorded),
      detail: extra[s.name],
    }];
  }));
}

/** A one-line summary for the status line: which stages are ports. */
export function summarise(choice) {
  const computed = PIPELINE.filter((s) => choice[s.name] === 'computed');
  return `${computed.length}/${PIPELINE.length} stages computed: ` +
    computed.map((s) => s.name).join(', ');
}
